import {useEffect,useMemo,useState} from 'react';
import './App.css';
const API='http://127.0.0.1:5001/api';
const money=n=>`₹${Number(n||0).toFixed(0)}`;
const fmt=t=>t?new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';

function App(){
 const [role,setRole]=useState(localStorage.getItem('sq_role')||'');
 const [email,setEmail]=useState(localStorage.getItem('sq_email')||'unser01@gmail.com'),[pass,setPass]=useState('12345678');
 const [view,setView]=useState('home'),[stalls,setStalls]=useState([]),[stall,setStall]=useState(null),[menu,setMenu]=useState([]),[cart,setCart]=useState({}),[orders,setOrders]=useState([]),[toast,setToast]=useState(''),[adminTab,setAdminTab]=useState('orders');
 const studentId=1;
 const api=async(path,opt={})=>{const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
 const loadStalls=async()=>{try{setStalls((await api('/stalls')).stalls)}catch(e){setToast(e.message)}};
 const loadMenu=async id=>{try{const j=await api(`/stalls/${id}/menu`);setStall(j.stall);setMenu(j.items);setView('menu')}catch(e){setToast(e.message)}};
 const loadOrders=async()=>{try{setOrders((await api(`/student/${studentId}/orders`)).orders)}catch(e){setToast(e.message)}};
 useEffect(()=>{if(!role)return;loadStalls();loadOrders();const t=setInterval(loadOrders,3000);return()=>clearInterval(t)},[role]);
 const login=async e=>{e.preventDefault();try{const j=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password:pass,role})});localStorage.setItem('sq_role',j.role);localStorage.setItem('sq_email',j.email);setRole(j.role);setView(j.role==='admin'?'admin':'home')}catch(x){setToast(x.message)}};
 const add=id=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
 const remove=id=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)-1)}));
 const total=useMemo(()=>menu.reduce((s,i)=>s+(cart[i.id]||0)*i.price,0),[menu,cart]);
 const place=async()=>{try{const items=Object.entries(cart).filter(([,q])=>q>0).map(([id,q])=>({menu_item_id:+id,quantity:q}));const o=await api('/orders',{method:'POST',body:JSON.stringify({student_id:studentId,service_point_id:stall.id,items})});setCart({});setToast(`Token ${o.token} created • ETA ${Math.round(o.eta_minutes)} min`);setView('orders');loadOrders()}catch(e){setToast(e.message)}};
 if(!role)return <Login role={role} setRole={setRole} email={email} setEmail={setEmail} pass={pass} setPass={setPass} login={login}/>;
 return <div className="app"><Header role={role} setView={setView} adminTab={adminTab} setAdminTab={setAdminTab}/>{role==='student'?<main>
   {view==='home'&&<StudentHome stalls={stalls} loadMenu={loadMenu}/>} 
   {view==='menu'&&<Menu stall={stall} menu={menu} cart={cart} add={add} remove={remove} total={total} place={place} back={()=>setView('home')}/>} 
   {view==='orders'&&<Orders orders={orders} loadOrders={loadOrders} api={api} setToast={setToast}/>} 
 </main>:<Admin api={api} stalls={stalls} orders={orders} tab={adminTab} setTab={setAdminTab} loadStalls={loadStalls} setToast={setToast} email={email}/>} {toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}</div>;
}
function Login({role,setRole,email,setEmail,pass,setPass,login}){return <div className="login"><div className="login-card"><div className="logo">⚡</div><h1>SmartQueue</h1><p>Campus Peak-Hour Intelligence</p><div className="problem-pill">200+ students · 45-minute break · visible wait</div><div className="rolepick"><button className={role==='student'?'sel':''} onClick={()=>setRole('student')}>Student</button><button className={role==='admin'?'sel':''} onClick={()=>setRole('admin')}>Admin</button></div><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input value={pass} onChange={e=>setPass(e.target.value)} type="password" placeholder="Password"/><button className="primary" disabled={!role}>Sign in as {role||'Student'}</button></form><small>Demo: unser01@gmail.com / 12345678</small></div></div>}
function Header({role,setView,adminTab,setAdminTab}){return <header><div className="brand"><b>⚡ SmartQueue</b><span>Know Your Wait. Plan Your Time.</span></div><nav>{role==='student'?<><button onClick={()=>setView('home')}>Stalls</button><button onClick={()=>setView('orders')}>My Orders</button></>:<><button className={adminTab==='orders'?'navactive':''} onClick={()=>setAdminTab('orders')}>Live Control</button><button className={adminTab==='menu'?'navactive':''} onClick={()=>setAdminTab('menu')}>Menu</button><button className={adminTab==='insights'?'navactive':''} onClick={()=>setAdminTab('insights')}>AI Insights</button></>}</nav><button className="logout" onClick={()=>{localStorage.removeItem('sq_role');localStorage.removeItem('sq_email');location.reload()}}>Logout</button></header>}
function StudentHome({stalls,loadMenu}){return <><section className="hero"><div><span className="eyebrow">GCU CAMPUS · PEAK-HOUR READY</span><h1>See the wait.<br/><em>Skip the physical queue.</em></h1><p>Order before you reach the counter. SmartQueue gives you a digital token, live position and estimated ready time so your 45-minute break stays yours.</p><div className="hero-chips"><span>✓ Digital token</span><span>✓ Live ETA</span><span>✓ Ready alert</span><span>✓ Less crowding</span></div></div></section><div className="section-head"><div><span className="eyebrow">SERVICE POINTS</span><h2>Choose where you need service</h2></div><span className="live">● LIVE</span></div><div className="grid">{stalls.map(s=><div className="stall card" key={s.id}><div className="icon">🍽️</div><h3>{s.name}</h3><p>{s.location}</p><div className="stall-meta"><span className={s.status==='OPEN'?'open':'closed'}>● {s.status}</span><span>Digital queue</span></div><button className="primary" disabled={s.status!=='OPEN'} onClick={()=>loadMenu(s.id)}>View Menu & Queue →</button></div>)}</div></>}
function Menu({stall,menu,cart,add,remove,total,place,back}){return <><button className="back" onClick={back}>← Back to service points</button><section className="menu-head"><div><span className="eyebrow">ORDERING FROM</span><h1>{stall.name}</h1><p>Select your items. A queue token is generated when you place the order.</p></div><div className="cartbox"><div><b>{money(total)}</b><span>{Object.values(cart).reduce((a,b)=>a+b,0)} items</span></div><button className="primary" disabled={!total} onClick={place}>Place Order →</button></div></section><div className="notice"><b>How it works:</b> Order → get token → monitor ETA → come to the assigned counter when READY.</div><div className="grid menu">{menu.map(i=><div className={`item card ${!i.available?'disabled':''}`} key={i.id}><div><span className="tag">{i.category}</span><h3>{i.name}</h3><b>{money(i.price)}</b><p>{i.available?'Available now':'Currently unavailable'}</p></div><div className="qty"><button disabled={!i.available} onClick={()=>remove(i.id)}>−</button><b>{cart[i.id]||0}</b><button disabled={!i.available} onClick={()=>add(i.id)}>+</button></div></div>)}</div></>}
function Orders({orders,loadOrders,api,setToast}){const active=orders.filter(o=>!['COMPLETED','CANCELLED'].includes(o.status));return <><section className="hero small"><span className="eyebrow">MY ORDERS · LIVE UPDATES</span><h1>Your food, without the queue.</h1><p>Keep the token. You only need to approach the collection counter when your order is ready.</p></section><div className="orders">{active.map(o=><OrderCard key={o.id} o={o} api={api} setToast={setToast} loadOrders={loadOrders}/>)}{!active.length&&<div className="empty">No active orders. Choose a service point and place your order.</div>}</div></>}
function OrderCard({o,api,setToast,loadOrders}){const stages=['PLACED','PREPARING','READY','COLLECTED'];const idx=stages.indexOf(o.status);const cancel=async()=>{try{await api(`/orders/${o.id}/cancel`,{method:'POST'});setToast('Order cancelled');loadOrders()}catch(e){setToast(e.message)}};return <div className="order card"><div className="order-top"><div><span className={`status status-${o.status.toLowerCase()}`}>{o.status}</span><h2>{o.token}</h2><p>{o.order_number} · {o.people_ahead||0} people ahead</p></div><strong>{money(o.total)}</strong></div><div className="queue-strip"><div><small>QUEUE POSITION</small><b>{o.position?`#${o.position}`:'Serving'}</b></div><div><small>EST. READY</small><b>{fmt(o.eta_at)}</b></div><div><small>ETA</small><b>{Math.max(0,Math.round(o.eta_minutes||0))} min</b></div><div><small>COUNTER</small><b>{o.counter?.number?`Counter ${o.counter.number}`:'Assigned on ready'}</b></div></div><div className="steps">{stages.map((s,i)=><span key={s} className={i<=idx?'done':''}>{i<=idx?'✓ ':'○ '}{s}</span>)}</div><div className="message"><b>Live message</b><p>{o.message||'Waiting for the canteen to start preparation.'}</p></div><div className="items">{o.items.map((x,i)=><span key={i}>{x.quantity}× {x.name}</span>)}</div>{['PLACED'].includes(o.status)&&<button className="cancel" onClick={cancel}>Cancel order</button>}</div>}
function Admin({api,stalls,orders,tab,setTab,loadStalls,setToast,email}){const [analytics,setAnalytics]=useState(null);const [refresh,setRefresh]=useState(0);useEffect(()=>{if(tab==='insights'||tab==='orders'){api('/admin/analytics/1').then(setAnalytics).catch(()=>{})}},[tab,orders,refresh]);const pending=orders.filter(o=>!['COMPLETED','CANCELLED'].includes(o.status));return <main><section className="hero admin"><span className="eyebrow">ADMIN CONTROL CENTER · LIVE</span><h1>Make the queue visible.<br/><em>Make the rush manageable.</em></h1><p>Operate orders, counters, preparation timing and demand from one control surface.</p><div className="hero-chips"><span>FIFO queue</span><span>Live ETA</span><span>Demand intelligence</span><span>Waste control</span></div></section><div className="tabs"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Live Orders <b>{pending.length}</b></button><button className={tab==='menu'?'active':''} onClick={()=>setTab('menu')}>Stalls & Menu</button><button className={tab==='insights'?'active':''} onClick={()=>setTab('insights')}>AI & Operations</button></div>{tab==='orders'?<LiveOrders pending={pending} stalls={stalls} api={api} setToast={setToast} setRefresh={setRefresh}/>:tab==='menu'?<MenuAdmin stalls={stalls} api={api} loadStalls={loadStalls} setToast={setToast} email={email}/>:<Insights analytics={analytics}/>}</main>}
function LiveOrders({pending,stalls,api,setToast,setRefresh}){return <div className="orders adminorders">{pending.map(o=><AdminOrder key={o.id} o={o} stalls={stalls} api={api} setToast={setToast} setRefresh={setRefresh}/>)}{!pending.length&&<div className="empty">All orders are complete. The queue is clear. 🎉</div>}</div>}
function AdminOrder({o,stalls,api,setToast,setRefresh}){const [eta,setEta]=useState(Math.round(o.eta_minutes||0));const [msg,setMsg]=useState(o.message||'');const [counter,setCounter]=useState(o.counter?.id||'');const counters=[{id:1,number:1,status:'OPEN'},{id:2,number:2,status:'OPEN'}];const update=async(status)=>{try{await api(`/orders/${o.id}/status`,{method:'POST',body:JSON.stringify({status,eta_minutes:eta,message:msg,counter_id:counter?+counter:undefined})});setToast(`${o.token} → ${status}`);setRefresh(x=>x+1)}catch(e){setToast(e.message)}};return <div className="order card adminorder"><div className="order-top"><div><span className={`status status-${o.status.toLowerCase()}`}>{o.status}</span><h2>{o.token}</h2><p>{o.order_number} · {o.people_ahead||0} ahead</p></div><strong>{money(o.total)}</strong></div><div className="items">{o.items.map((x,i)=><span key={i}>{x.quantity}× {x.name}</span>)}</div><div className="control-grid"><label>ETA minutes<input type="number" min="0" value={eta} onChange={e=>setEta(e.target.value)}/></label><label>Collection counter<select value={counter} onChange={e=>setCounter(e.target.value)}><option value="">Auto / assign later</option>{counters.map(c=><option key={c.id} value={c.id}>Counter {c.number} · {c.status}</option>)}</select></label><label className="wide">Message to student<input value={msg} onChange={e=>setMsg(e.target.value)} placeholder="e.g. Ready at Counter 2"/></label></div><div className="admin-actions"><button onClick={()=>update('PREPARING')}>▶ Start Preparing</button><button onClick={()=>update('READY')}>✓ Mark Ready</button><button onClick={()=>update('COLLECTED')}>↗ Collected</button><button className="done" onClick={()=>update('COMPLETED')}>DONE ✓</button></div><div className="mini-meta">Current ETA: <b>{Math.round(o.eta_minutes||0)} min</b> · Ready: <b>{fmt(o.eta_at)}</b> · Token stays FIFO</div></div>}
function MenuAdmin({stalls,api,loadStalls,setToast,email}){const [stallName,setStallName]=useState(''),[item,setItem]=useState({stall:stalls[0]?.id||1,name:'',price:'',stock_target:40});const addStall=async()=>{if(!stallName.trim())return;try{await api('/admin/stalls',{method:'POST',body:JSON.stringify({name:stallName,created_by_email:email})});setStallName('');loadStalls();setToast('Service point added ✓')}catch(e){setToast(e.message)}};const addItem=async()=>{try{await api(`/admin/stalls/${item.stall}/items`,{method:'POST',body:JSON.stringify(item)});setItem({...item,name:'',price:''});setToast('Menu item added ✓')}catch(e){setToast(e.message)}};const removeStall=async s=>{if(s.created_by_email?.toLowerCase()!==email?.toLowerCase()){setToast('Only the creator can remove this stall');return}if(!window.confirm(`Remove ${s.name}? It will disappear from active stalls.`))return;try{await api(`/admin/stalls/${s.id}`,{method:'DELETE',body:JSON.stringify({email})});if(item.stall===s.id)setItem(x=>({...x,stall:stalls.find(v=>v.id!==s.id)?.id||1}));loadStalls();setToast(`${s.name} removed ✓`)}catch(e){setToast(e.message)}};return <div className="management"><div className="card form"><span className="eyebrow">OPERATIONS</span><h2>Add service point</h2><input placeholder="Stall / counter name" value={stallName} onChange={e=>setStallName(e.target.value)}/><button className="primary" onClick={addStall}>+ Add Service Point</button></div><div className="card form"><span className="eyebrow">MENU CONTROL</span><h2>Add menu item</h2><select value={item.stall} onChange={e=>setItem({...item,stall:+e.target.value})}>{stalls.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input placeholder="Item name" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><div className="two"><input placeholder="Price ₹" type="number" value={item.price} onChange={e=>setItem({...item,price:e.target.value})}/><input placeholder="Peak stock target" type="number" value={item.stock_target} onChange={e=>setItem({...item,stock_target:e.target.value})}/></div><button className="primary" onClick={addItem}>+ Add Item</button></div><div className="stalllist">{stalls.map(s=><div className="card" key={s.id}><div className="stall-card-head"><div><h3>🍽️ {s.name}</h3><p>{s.location}</p></div>{s.created_by_email?.toLowerCase()===email?.toLowerCase()&&<button className="danger" onClick={()=>removeStall(s)}>Remove Stall</button>}</div><span className="open">● {s.status}</span><small className="owner-note">{s.created_by_email?.toLowerCase()===email?.toLowerCase()?'Created by you · You can remove it':'Created by another admin · Removal restricted'}</small></div>)}</div></div>}
function Insights({analytics}){if(!analytics)return <div className="empty">Loading intelligence…</div>;const max=Math.max(1,...analytics.demand.map(x=>x.sold));return <div className="insights"><div className="metric-grid"><Metric n={analytics.pending} l="Live orders"/><Metric n={`${analytics.avg_eta} min`} l="Average ETA"/><Metric n={`${analytics.active_counters}/${analytics.total_counters}`} l="Active counters"/><Metric n={money(analytics.revenue)} l="Tracked sales"/></div><div className="insight-grid"><div className="card"><span className="eyebrow">DEMAND ENGINE</span><h2>Peak preparation view</h2><p className="muted">Expected peak window: <b>{analytics.peak_window}</b></p>{analytics.demand.map(x=><div className="barrow" key={x.name}><div><span>{x.name}</span><b>{x.sold} sold · {x.waste} waste</b></div><div className="bar"><i style={{width:`${Math.max(6,x.sold/max*100)}%`}}/></div><small className={x.risk==='HIGH'?'risk':''}>{x.risk} waste risk</small></div>)}</div><div className="card decision"><span className="eyebrow">DECISION ENGINE</span><h2>What the system tells staff</h2><div className="decision-row"><b>Queue</b><span>{analytics.pending>12?'HIGH CONGESTION':'MANAGEABLE'}</span></div><div className="decision-row"><b>Capacity</b><span>{analytics.active_counters<analytics.total_counters?'Open a counter if demand rises':'Counters available'}</span></div><div className="decision-row"><b>Waste</b><span>Use live demand before batch preparation.</span></div><div className="decision-row"><b>Policy</b><span>FIFO + live ETA + counter assignment.</span></div><div className="callout">{analytics.waste_message}</div></div></div></div>}
function Metric({n,l}){return <div className="metric card"><b>{n}</b><span>{l}</span></div>}
export default App;
